export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS'

export const LIST_CUSTOMERS_SUCCESS = 'LIST_CUSTOMERS_SUCCESS'

export const GET_CUSTOMER_SUCCESS = 'GET_CUSTOMER_SUCCESS'

export const UPDATE_QUERY_CUSTOMER = 'UPDATE_QUERY_CUSTOMER'
