export const CREATE_TABLE_SUCCESS = 'CREATE_TABLE_SUCCESS'

export const LIST_TABLES_SUCCESS = 'LIST_TABLES_SUCCESS'

export const GET_TABLE_SUCCESS = 'GET_TABLE_SUCCESS'

export const UPDATE_QUERY_TABLE = 'UPDATE_QUERY_TABLE'

export const UPDATE_TABLE_SUCCESS = 'UPDATE_TABLE_SUCCESS'
