export const CREATE_TOURNAMENT_SUCCESS = 'CREATE_TOURNAMENT_SUCCESS'

export const LIST_TOURNAMENTS_SUCCESS = 'LIST_TOURNAMENTS_SUCCESS'

export const GET_TOURNAMENT_SUCCESS = 'GET_TOURNAMENT_SUCCESS'

export const UPDATE_QUERY_TOURNAMENT = 'UPDATE_QUERY_TOURNAMENT'

export const UPDATE_TOURNAMENT_SUCCESS = 'UPDATE_TOURNAMENT_SUCCESS'
